name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Ensure S3 bucket for Terraform state exists
        run: |
          aws s3api head-bucket --bucket devops-accelerator-platform-tf-state 2>/dev/null || \
          aws s3api create-bucket \
            --bucket devops-accelerator-platform-tf-state \
            --region ${{ secrets.AWS_REGION }} \
            --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}

      - name: Ensure DynamoDB table for Terraform lock exists
        run: |
          if ! aws dynamodb describe-table --table-name devops-accelerator-tf-locker >/dev/null 2>&1; then
            aws dynamodb create-table \
              --table-name devops-accelerator-tf-locker \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST \
              --region ${{ secrets.AWS_REGION }}
          fi

      - name: Terraform Init
        run: |
          cd infra/terraform
          terraform init -reconfigure

      - name: Terraform Validate
        run: |
          cd infra/terraform
          terraform validate

      - name: Terraform Plan & Apply
        run: |
          cd infra/terraform
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
